apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alloy
  namespace: observability
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: homelab.local
      http:
        paths:
          - path: /otlp(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: alloy-otlp
                port:
                  number: 4318
  tls:
    - hosts:
        - homelab.local
      secretName: homelab-tls
