apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: observability
spec:
  instances: 3
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  storage:
    storageClass: local-path
    size: 5Gi
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      secret:
        name: grafana-db-secret
  postgresql:
    parameters:
      max_connections: "200"
