tempo:
  reportingEnabled: false
  structuredConfig:
    compactor:
      compaction:
        block_retention: 168h

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: rook-ceph-rgw-my-store.storage.svc
      access_key: ceph-obs-access
      secret_key: ceph-obs-secret
      insecure: true

ingester:
  replicas: 2
  config:
    replication_factor: 2
  persistentVolume:
    storageClass: ceph-block
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 10m
      memory: 256Mi

distributor:
  replicas: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 10m
      memory: 128Mi

compactor:
  replicas: 1
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 10m
      memory: 128Mi

querier:
  replicas: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 10m
      memory: 128Mi

queryFrontend:
  replicas: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 10m
      memory: 128Mi

memcached:
  enabled: false

minio:
  enabled: false
