apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  namespace: operations
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "2147483647"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "2147483647"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "2147483647"
spec:
  ingressClassName: nginx
  rules:
    - host: homelab.local
      http:
        paths:
          - path: /headlamp
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 80
  tls:
    - hosts:
        - homelab.local
      secretName: homelab-tls
