config:
  baseURL: /headlamp
  oidc:
    clientID: "edWXswNHdvZ3ivhXdGtzLYzM9ujmDWqD4ZEn6tbb"
    clientSecret: "ZCz6wEERsbVbVTowjNcxYjDbQSaxoPMuHiTos6pIGQuUCxNYDMsnjCbrVX6RgBeMZkaXYQzqAHrN9VBc04kKO6QM7xnprUQrZregxfcsW2YTKupGbhF7GiXDzKKK7C6P"
    issuerURL: "https://homelab.local/authentik/application/o/headlamp/"
    scopes: "openid profile email offline_access"
  extraArgs:
    - "-oidc-ca-file=/etc/ssl/certs/homelab-ca.crt"
volumes:
  - name: homelab-ca
    configMap:
      name: homelab-ca
volumeMounts:
  - name: homelab-ca
    mountPath: /etc/ssl/certs/homelab-ca.crt
    subPath: ca.crt
service:
  type: ClusterIP
  port: 80
