config:
  baseURL: /headlamp
  oidc:
    clientID: "WioRP7AobTevOKeg1mt69faLsY3DqugU9Kut8rFN"
    clientSecret: "72klmuwVWcm2o2XwiWkrOU8vHuHjjR5ELUfYGVAaqpSaZYphNAdp7PLhqQAOMDOTyVMaufJ8j66LK7hUXRQmY9L6KH2HhVWFlQJX3d6Db592d0MEhPg9aYNDpQKi1w6R"
    issuerURL: "https://homelab.local/authentik/application/o/headlamp/"
    scopes: "openid profile email offline_access"
  extraArgs:
    - "-oidc-ca-file=/etc/ssl/certs/homelab-ca.crt"
volumes:
  - name: homelab-ca
    configMap:
      name: homelab-ca
volumeMounts:
  - name: homelab-ca
    mountPath: /etc/ssl/certs/homelab-ca.crt
    subPath: ca.crt
service:
  type: ClusterIP
  port: 80
