apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-probe
  namespace: observability
data:
  config.alloy: |-
    prometheus.exporter.blackbox "external" {
      config = `
        modules:
          icmp:
            prober: icmp
            timeout: 5s
          http_2xx:
            prober: http
            timeout: 5s
            http:
              valid_status_codes: []
      `

      target {
        name    = "windows"
        address = "192.168.1.100"
        module  = "icmp"
        labels  = {
          job = "external-probe",
          os  = "windows",
        }
      }
    }

    prometheus.scrape "blackbox_external" {
      targets         = prometheus.exporter.blackbox.external.targets
      forward_to      = [prometheus.relabel.blackbox_job.receiver]
      scrape_interval = "30s"
    }

    prometheus.relabel "blackbox_job" {
      forward_to = [prometheus.remote_write.mimir.receiver]

      rule {
        target_label = "job"
        replacement  = "external-probe"
      }
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-gateway.observability.svc/api/v1/push"
      }
    }
