apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc-secret
  namespace: operations
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  clientSecret: "2o3BLVwFVjk4WhY2ZADqesv8K5uwC2vqERt0PxdA4eWUbcIuIIFspYXXOX1EdZzKef1PNq69kBOJL7qRSQkU9mxW1QqPmTIc02MXcMe0kS4chF9X5M1dJ8t0qmrm50Vy"
