apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc-secret
  namespace: operations
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  clientSecret: "sFGXbB7pw2PF9XYwLuICllpEXXmccX8I4SCS48GiWRkx8aAzMnWeFPz9XKiLFUd8SdDsqT9l4fdZVm0AGN2f9Ltu7KrwJZwNekNaHJNw6Se3DBokFZhScANF1mMZ6R7e"
