apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc-secret
  namespace: operations
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  clientSecret: "9m0healRrvhsSJpJpbTfRhE1rktVOQHHPAEIwYP1q5zv1Qg1VJ5w0WKdtbnTx5KgxLhoBgfU2wHcyBRFUwaBrYKnjtD4Xhoi3ZIi3JZkilo5ua3T23m8dOT9O0hZLTC5"
