apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-oauth2-secret
  namespace: database
type: Opaque
stringData:
  OAUTH2_CLIENT_ID: "45BhLOeUTSQMnKgkbW6bffiybp9k6m2smhYxkDtE"
  OAUTH2_CLIENT_SECRET: "6w1Mfq5zDAP3SIfY3dxntxmTHBHXkBTaRMZKvqNJn3R7qbjhdhZCUM44nN8UGM9EkunkcIzZ9vg8La4R6lhRa9INLUTNdEJvchaHeBTQxTSNIR2L1QmocI8pU5xFIC6s"
