apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-oauth2-secret
  namespace: database
type: Opaque
stringData:
  OAUTH2_CLIENT_ID: "<PGADMIN_CLIENT_ID>"
  OAUTH2_CLIENT_SECRET: "<PGADMIN_CLIENT_SECRET>"
