apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-oauth2-secret
  namespace: database
type: Opaque
stringData:
  OAUTH2_CLIENT_ID: "ywLm2ZqurZ7HOwGIUUDqPGt4oSQ1ueyidRkwstF2"
  OAUTH2_CLIENT_SECRET: "fkMaV149IO7Bgrnke96N2W77I4ECkmTqE11SEnQGkS2tR0NvGWW13oTgz5Rd7X9iZRvnhZez0EtSh9LIZJZgaviK1vohoMlKsbSawUH8wKAbsjWvDUs2ObFjMixt9Ww4"
