mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: rook-ceph-rgw-my-store.storage.svc
          access_key_id: ceph-obs-access
          secret_access_key: ceph-obs-secret
          insecure: true
    blocks_storage:
      s3:
        bucket_name: mimir-blocks
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager
    ruler:
      evaluation_interval: 1m
      poll_interval: 2m
    ingest_storage:
      enabled: false
    ingester:
      push_grpc_method_enabled: true
      ring:
        replication_factor: 2
    limits:
      compactor_blocks_retention_period: 168h
      out_of_order_time_window: 10m
      ingestion_rate: 100000
      ingestion_burst_size: 1000000

distributor:
  replicas: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir
              app.kubernetes.io/component: distributor
          topologyKey: kubernetes.io/hostname

ingester:
  replicas: 2
  persistentVolume:
    storageClass: ceph-block
    size: 10Gi
  zoneAwareReplication:
    enabled: false
    migration:
      replicas: 0
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir
              app.kubernetes.io/component: ingester
          topologyKey: kubernetes.io/hostname

querier:
  replicas: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir
              app.kubernetes.io/component: querier
          topologyKey: kubernetes.io/hostname

query_frontend:
  replicas: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 258Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir
              app.kubernetes.io/component: query-frontend
          topologyKey: kubernetes.io/hostname

store_gateway:
  replicas: 2
  persistentVolume:
    storageClass: ceph-block
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir
              app.kubernetes.io/component: store-gateway
          topologyKey: kubernetes.io/hostname

compactor:
  replicas: 1
  persistentVolume:
    storageClass: ceph-block
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

alertmanager:
  enabled: true
  replicas: 1
  persistentVolume:
    storageClass: ceph-block
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  fallbackConfig: |
    global:
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: tmkznrs@gmail.com
      smtp_auth_username: tmkznrs@gmail.com
      smtp_auth_password: kqawoiqyouurfzbe
      smtp_require_tls: true
    route:
      receiver: gmail
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: gmail
        email_configs:
          - to: tmkznrs@gmail.com
            send_resolved: true

ruler:
  enabled: true
  replicas: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir
              app.kubernetes.io/component: ruler
          topologyKey: kubernetes.io/hostname

kafka:
  enabled: false

minio:
  enabled: false
