apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: mimir
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir-gateway.observability.svc/prometheus
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 60s
