apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secret
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "9GflpOYBrRTsMdJULeNmAPIK0D4nhq4lVZgZeme3"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "og34Rsu7WufOySSMG5BXp6Eo8ZjPioCT2TB8x7bS72urGrQ23wPZAWnKjv4oFTtjSVLbHRw88JeSzSvjHuQN8v9PDaJPDP4EzkJPrePcZDVSrAJh3wS2fS5R9zOjsn4E"
