apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secret
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "PLACEHOLDER"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "PLACEHOLDER"
