apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  rules:
    - host: homelab.local
      http:
        paths:
          - path: /authentik
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 9000
  tls:
    - hosts:
        - homelab.local
      secretName: homelab-tls
