authentik:
  secret_key: "<AUTHENTIK_SECRET_KEY>"
  bootstrap_password: "<BOOTSTRAP_PASSWORD>"
  bootstrap_token: "<BOOTSTRAP_TOKEN>"
  postgresql:
    host: "postgres-cluster-rw.database.svc"
    name: authentik
    user: authentik
    password: "<AUTHENTIK_DB_PASSWORD>"
  redis:
    host: "{{ .Release.Name }}-redis-master"

server:
  env:
    - name: AUTHENTIK_WEB__PATH
      value: "/authentik/"
  startupProbe:
    httpGet:
      path: /authentik/-/health/live/
      port: http
  readinessProbe:
    httpGet:
      path: /authentik/-/health/ready/
      port: http
  livenessProbe:
    httpGet:
      path: /authentik/-/health/live/
      port: http
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 1Gi

worker:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 1Gi

blueprints:
  configMaps:
    - authentik-blueprints

postgresql:
  enabled: false

redis:
  enabled: true
  master:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
