tenant:
  name: minio-observability

  configSecret:
    name: minio-env-config
    accessKey: minio
    secretKey: minio12345

  env:
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://homelab.local/authentik/application/o/minio/.well-known/openid-configuration"
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: "eZbfEpi1s1gF6iV32dRuUSyfOqKtBXgZeCKxetWl"
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      value: "rcQOU0xKDtlZEdUBCxfBmVZf6vHjw9INHkTZLxcmHmhnVLALgqGDUqG9ADi4xeHbtwETmSQJhUVLQHE6N0jzdhS6Q5feuIZMg6dwMZUmJGiaAfi9Apyr8MF7830haulv"
    - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
      value: "https://homelab.local/minio-console/oauth_callback"
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "openid,profile,email,minio_policy"
    - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME
      value: "Authentik"

  pools:
    - name: pool-0
      servers: 3
      volumesPerServer: 2
      size: 50Gi
      storageClassName: local-path
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 500m
      env:
        - name: GOMEMLIMIT
          value: "900MiB"
        - name: GOGC
          value: "20"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - minio-observability
              topologyKey: kubernetes.io/hostname

  buckets:
    - name: loki-chunks
    - name: loki-ruler
    - name: loki-admin
    - name: mimir-blocks
    - name: mimir-ruler
    - name: mimir-alertmanager
    - name: tempo-traces

  additionalVolumes:
    - name: homelab-ca
      configMap:
        name: homelab-ca

  additionalVolumeMounts:
    - name: homelab-ca
      mountPath: /tmp/certs/CAs
      readOnly: true

  certificate:
    requestAutoCert: false
